### ISSUE TITLE
Smart Banner usage question

### ISSUE THREAD

**Issue by dm77** [BranchMetrics/Web-SDK#13]
Hi I am testing the smart banner usage and couldn't get it to work. Sorry if I am being stupid. This is my banner call:

```javascript
 branch.banner({
    icon: 'http://icons.iconarchive.com/icons/wineass/ios7-redesign/512/Appstore-icon.png',
    title: 'Branch Demo App',
    description: 'The Branch demo app!',
    openAppButtonText: 'Open',         
    downloadAppButtonText: 'Download', 
    iframe: true,                      
    showMobile: true,                
    showDesktop: true
}, {
    type: 1,
    data: {
        mydata: 'something'
    }
});
```

But I am seeing the following error in the Chrome desktop browser console and also in android chrome browser logs (adb log):

```
Uncaught TypeError: Cannot read property 'addEventListener' of null        branch-v1.0.0.min.js:15
 ba                                    branch-v1.0.0.min.js:37 
U.banner                           branch-v1.0.0.min.js:37 
(anonymous function)       branch-v1.0.0.min.js:37 
(anonymous function)   
```

**Comment by dmitrig01** [comment]
Thanks for the report – we're looking into this right now.

**Comment by dmitrig01** [comment]
@dm77 we've just released v1.0.1, which fixes this. just update your init script to point to https://cdn.branch.io/branch-v1.0.1.min.js and it should work!

**Comment by dm77** [comment]
Confirmed. Works well now. Thanks so much for the quick fix.

**Comment by scotthasbrouck** [comment]
Great to hear, let us know if you run into any other issues
