### ISSUE TITLE
Send SMS not working for white labeled url

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Web-SDK#15]
In the console I am getting:

```
GET https://bnc.lt/http://b.weesnap.com/l/3erzqWE-8q?click=click 404 (Not Found) build.js:1025 
XHRRequest build.js:1032 
api build.js:1071 
(anonymous function) build.js:636 
b build.js:644 
Queue build.js:1067 
Branch._api build.js:1158 
Branch.linkClick build.js:1185 
(anonymous function) build.js:1148 
(anonymous function) build.js:1073 
(anonymous function) build.js:1016 
f.onreadystatechange 2015-03-05 16:19:13.330 build.js:1159 
Uncaught TypeError: Cannot read property 'click_id' of undefined
```

you can see it is trying a strange url which is a composition of bnc and b.weesnap.com.

**Comment by kenleezle** [comment]
udpated the comment with a better example url. my weesnap url works (though its private so you guys won't be able to get to it.) but when i copy it out:

http://b.weesnap.com/l/3erzqWE-8q

and load it in my browser, it loads fine.

**Comment by kenleezle** [comment]
interestingly this works as well:
https://bnc.lt//l/3erzqWE-8q

So the only thing that doesn't work is the frankenstein:
https://bnc.lt/http://b.weesnap.com/l/3erzqWE-8q

@scotthasbrouck @dmitrig01

**Comment by dmitrig01** [comment]
woah, yikes, that frankenstein is not supposed to exist. looks like somebody is trying to be a relative path when they sholud be absolute. @scotthasbrouck can you hop on this?

**Comment by scotthasbrouck** [comment]
@kenleezle thanks for finding this... I'll let you know as soon as this is resolved!

**Comment by kenleezle** [comment]
thanks

**Comment by kenleezle** [comment]
can i have an eta on that fix?

**Comment by dmitrig01** [comment]
1-2 hour

**Comment by kenleezle** [comment]
wow thats great! thanks!

**Comment by scotthasbrouck** [comment]
hey @kenleezle we just pushed a fix. Give that a spin and that should take care of the incorrect path on your whitelabeled domain!

**Comment by dmitrig01** [comment]
@kenleezle er, give me like 10 mins and i will package up a bower/npm/etc release

**Comment by dmitrig01** [comment]
All right - release v1.1.0 on bower - take it for a spin and let us know if you're still seeing issues

**Comment by kenleezle** [comment]
on it

**Comment by kenleezle** [comment]
sms is fixed.

**Comment by kenleezle** [comment]
I'm going to open up an issue on a feature request related to all this for @scotthasbrouck

**Comment by scotthasbrouck** [comment]
Great to hear it's working! Sounds good, I'll have that for you tonight

**Comment by kenleezle** [comment]
awesome @scotthasbrouck thanks!
