### ISSUE TITLE
Add Banner Option: showAndroid

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Web-SDK#17]
We only have an iphone app. For android users we have a mobile friendly web page.

By using the banners we will be frustrating android users by dangling a download app call to action in front of them, when there is really no android app available.

This is pretty important for us, because we spent a lot of time making the mobile web app look very good and native, so this fake call to action really breaks us.

Any work arounds until the option is in? Or do you think this option is something you might introduce soon?

**Comment by kenleezle** [comment]
Needless to say this is higher priority than the #16

**Comment by dmitrig01** [comment]
We should probably do a corresponding showiOS :-)

**Comment by kenleezle** [comment]
makes sens

**Comment by dmitrig01** [comment]
closing in favor of #18. we'll porbably release a 1.1.2 or 1.2.0 tomorrow with it
