### ISSUE TITLE
smart banner option: iframe = false not working

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Web-SDK#19]
Uncaught TypeError: Cannot read property 'getElementById' of null

in build.js:1028

I initially was using the recommended iframe option, however the banner was overlapping the controls on my photo gallery viewer. I am using photoswipe (currently one of the most popular open source gallery libs) https://github.com/dimsemenov/photoswipe

I was trying iframe: false to see if that would fix my issue.

**Comment by kenleezle** [comment]
one way to help mitigate this would be if i had banner show() and hide() methods to call. i could hide the banner when the user enters gallery mode, and then show it when the user exits gallery mode.

**Comment by dmitrig01** [comment]
hrm, the fact that this is broken is not good. additionally, show and hide methods are a great idea.

cc @scotthasbrouck

**Comment by kenleezle** [comment]
ok, we tracked it down to your z-index of 99999, if that was configurable that would help

**Comment by kenleezle** [comment]
yes, i can confirm that setting the z-index of your iframe to 0 resolves our issue

**Comment by dmitrig01** [comment]
ah, interesting. maybe we should pick some kind of intermediate value that's not quite 99999, but still pretty high. i don't think it's worth making it configurable, as you can just override it with CSS, but we should at least document it

**Comment by kenleezle** [comment]
i'm fine with setting the z-index manually as i did. it seems to be working. you can close this.

**Comment by dmitrig01** [comment]
Cool - thanks!
