### ISSUE TITLE
App Name doesn't appear on Smart Banner for iphone 4/5/6

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Web-SDK#22]
It seems that you have a media query which is deciding that any screen size smaller than about what the iphone 6 plus is should not display the app name, and only the app icon.

This appears broken to me.

Attaching screenshots..

Working (iphone 6 plus):

![screen shot 2015-03-23 at 4 24 29 pm](https://cloud.githubusercontent.com/assets/1616389/6789750/24389942-d179-11e4-8196-b809c7c4ea14.png)

App Name not displayed (iphone 6):
![screen shot 2015-03-23 at 4 24 08 pm](https://cloud.githubusercontent.com/assets/1616389/6789753/29bc49d6-d179-11e4-8ef5-9549c5522830.png)

**Comment by kenleezle** [comment]
I shortened my app name and description and now it shows up on screen sizes all the way down to the iphone 3gs.

**Comment by dmitrig01** [comment]
@scotthasbrouck

**Comment by polaski** [comment]
The default width for .left and .right classes are like 40 something % each, anything that goes over that width gets wrapped to the next line, and since it's overflow:hidden, it's not displayed. I looked all over the documentation and code but couldn't find a way to customize the banner at all. Ultimately I had to hack it like below and it kind of works, but it still feels very dirty.

       setTimeout(function(){
         $("iframe").contents().find(".left").css("width", "70%");
         $("iframe").contents().find(".right").css("width", "25%");
       },1000);

**Comment by dmitrig01** [comment]
you can choose iframe:false to be able to customize it better - try that?

**Comment by polaski** [comment]
Maybe I'm missing something but iframe:false doesn't seem to work. I tried every version possible. Right now I'm running the latest 1.3.0 and it still renders them in an iframe

**Comment by dmitrig01** [comment]
hrm, I believe there was a bug there, but I thought we fixed it. let me take a look in a bit

**Comment by scotthasbrouck** [comment]
@polaski can you send a snippet of how you're calling the banner method with iframe:false, or any other context? I'm not able to reproduce the option not working. In the mean time.. I'll also work on the CSS for this to come up with a better solution that won't cause the entire app name and description to wrap outside the banner.

**Comment by polaski** [comment]
I think I figured it out. I thought these api calls were synchronous but actually they're asynchronous. So to clarify, I'm supposed to call banner() and link() methods inside init()'s callback, right?

**Comment by dmitrig01** [comment]
We're actually working on that right now, but for the moment, you do need to do that unfortunately.

**Comment by scotthasbrouck** [comment]
@kenleezle Just posted a CSS fix as v1.3.1. The app title and description should now line break and wrap, rather than just overflow outside the banner. Give that a try and let me know if you're still having porblems with it!
