### ISSUE TITLE
XMLHttpRequest cannot load https://api.branch.io/v1/open

### ISSUE THREAD

**Issue by polaski** [BranchMetrics/Web-SDK#23]
I am using Web SDK to create banner and links. Today I am suddenly getting the following error when I try to create banner and links. Nothing on my side has changed and I can say it was working fine till yesterday. Is there something wrong? I am concerned because I just pushed a production app using branch links. 

[Error] XMLHttpRequest cannot load https://api.branch.io/v1/open. Origin [REDACTED] is not allowed by Access-Control-Allow-Origin.

**Comment by scotthasbrouck** [comment]
@polaski What browser/version did this error occur in? Also, was the page hosted on http, or https?

**Comment by derrickstaten** [comment]
@polaski is this still an issue for you? If so, can you post more information on your browser and which SDK version you're using?

**Comment by polaski** [comment]
Sorry for the delay, yes it's working now. I don't know why it didn't work before. I didn't change anything but now it's back.
