### ISSUE TITLE
Method To Close Banner

### ISSUE THREAD

**Issue by IsaiahJTurner** [BranchMetrics/Web-SDK#29]
I'd like to be able to close the banner using javascript.

An example for when this is needed is Ember.js applications. The user could click a link to a 404 page but the banner would still show because with Ember.js the page does not refresh, only the content within the <body> updates.

**Comment by dmitrig01** [comment]
This is a great idea – we should do this.

Maybe there sholud be some easier way for you to bind it directly to embed, so instead of adding commands for when to show and hide the banner, you can just say "while this page is showing, the banner should be showing"?

**Comment by scotthasbrouck** [comment]
Agreed, fantastic idea. @dmitrig01 we could just pass it in as an init options, like `showBanner: true`. We don't currently have an options argument in init, but I think we should just go ahead and add one. I'm sure they'll be other init option scenarios in the future.

But I think it would still be useful to also have a `close()` method for the banner. I could imagine a scenario where the banner is being shown on top of a web app, and it would be desirable to hide the banner after X seconds, or after the user interacts with the UI. Thoughts on that @IsaiahJTurner and @dmitrig01 before I start working on it?

**Comment by IsaiahJTurner** [comment]
@scotthasbrouck I don't think init needs options but maybe I'm not fully understanding your thinking behind that. Definitely in favor of `branch.close()`, though.

**Comment by dmitrig01** [comment]
This is fixed in version 1.4.0 -- we now have a `branch.closeBanner()` function which will do exactly that :-)
