### ISSUE TITLE
Fingerprinting js is not documented but a hard dependency

### ISSUE THREAD

**Issue by Thinkscape** [BranchMetrics/Web-SDK#3]
Fingerprinting bit that uses server side (`_r`) and its invocation is not included in the SDK (unless you paste that initialization blob).

It seems that it's required for SDK to work, understandably. Even if it requires the server side call, it should be performed on init() or in otherwise controllable fashion.

**Comment by dmitrig01** [comment]
this is fixed in the v2 branch as well.
