### ISSUE TITLE
Does this work in node.js?

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Web-SDK#35]
thanks in advance.

**Comment by dmitrig01** [comment]
Not currently – what's your use case?

**Comment by kenleezle** [comment]
our user wants to invite his/her friends to use our app.
he opens up a multi-share select contact picker.
he selects 10 friends and presses invite.
We want to create 10 different branch links for this case, to leverage the power of branch.io :+1: 

We figured this should be done on the server instead of in our ios client for scaling reasons.

How would you advise handling this?
It looks like the ios sdk does not provide access to the bulk rest endpoint you have (POST /v1/url/bulk/:branch_key)

**Comment by kenleezle** [comment]
@zachlloyd

**Comment by dmitrig01** [comment]
Ah -- yep. I have plans to make a node.js client, but nothing concrete right now. I would just do a server-to-server integration: https://github.com/BranchMetrics/Branch-Public-API. You can either use the bulk creation api or just create one-off links – creating 10 links isn't so bad. When you start creating hundreds or thousands, that's when I would recommend switching to one-off links :-)

But, if you do want to do use it, I like [superagent](https://github.com/visionmedia/superagent), so here's a small code snippet:

```
var request = require('superagent');
var BRANCH_KEY = '...';
request('https://api.branch.io/v1/url/bulk/' + BRANCH_KEY)
   .send([
      { campaign: 'abc', channel: 'def', identity: 'your_user_id' }
   ]).end(function(err, res) {
      console.log(err, res);
   });
```

**Comment by tejasmanohar** [comment]
@dmitrig01 My app is doing the same thing with invites as @kenleezle. Would you recommend bulk creating the links on the server-side (node.js backend) or client-side (iOS)?

**Comment by kenleezle** [comment]
@tejasmanohar i implemented what @dmitrig01 suggested fwiw

**Comment by aaustin** [comment]
I'm going to close this issue. I hope all is well with you guys.
