### ISSUE TITLE
link data passed to branch.init callback is a JSON-encoded string

### ISSUE THREAD

**Issue by jonklein** [BranchMetrics/Web-SDK#40]
When trying to extract the link data using the web SDK, I'm finding a JSON-encoded string of the parameters rather than the parsed param hash.  Here's an example

```
"{"$marketing_title":"Test link with user context","sender_avatar_url":"https://placekitten.com/g/200/202","sender_name":"Whiskers McFluffybelly"}"
```

It's possibly that this is the expected behavior, but it's a bit odd.

**Comment by scotthasbrouck** [comment]
This is a relic from the old version of the SDK that we intend to change in version 2.x. In the meantime, I'll add an option you can set that will automatically parse the data property. I'll keep you posted when it's ready.

**Comment by dmitrig01** [comment]
This will be in the newest release. You're right that it's very odd. In the next version (will release either today or tomorrow), you will be able to use data_parsed, which is the parsed version of this :-)
