### ISSUE TITLE
cordova: identity_id not sent on open

### ISSUE THREAD

**Issue by Deminetix** [BranchMetrics/Web-SDK#46]
All works well on first install of the cordova app on android, until I force-quit/restart the app. Obviously, the difference is that the first open sends an install request, and subsequent opens send an open request with the identity_id etc.

The actual error i get is `Error: API request /v1/open missing parameter identity_id`

On this line (260:3_branch.js):
`if (utils.readKeyValue('identity_id', self._permStorage)) {`
the value exists and makes it run `self._api()`

The problem is that `self._api()` doesn't get the `identity_id` in the same fashion: (124:3_branch.js)
`if (((resource.params && resource.params['identity_id']) || (resource.queryPart && resource.queryPart['identity_id'])) && this.identity_id) { obj['identity_id'] = this.identity_id; }`

If i replace this line with `obj['identity_id'] = utils.readKeyValue("identity_id", this._permStorage)` then it works... well... that part does. It then cascades into other issues with `device_fingerprint_id` also missing.

**Comment by dmitrig01** [comment]
Ahh, good catch. I'll fix this over the next day or two.

**Comment by dmitrig01** [comment]
(unless you need it sooner - let me know)

**Comment by dmitrig01** [comment]
fyi – this is fixed in 1.5.0, released this afternoon!

**Comment by sangeetjass** [comment]
I have a situation where, I have two apps, one merchant facing and another consumer facing. I have branch registered for consumer facing app, but I want merchant app to send the referral invite link.  Branch SDK when initialised on consumer facing app (registered with branch) works fine, but when initialised on the merchant app, it gives API request /v1/open missing parameter device_fingerprint_id error.  I need to simply generate referral link, I used javascript sdk, it worked fine, but it kept giving an alert that I need to install cordova plugin. What should i do?
