### ISSUE TITLE
How to inject cookie/id within branch link before transported to app store from webpage?

### ISSUE THREAD

**Issue by sirvon** [BranchMetrics/Web-SDK#6]
Ok, here's the flow...

I have a cookie/id already created for the user, upon
first open of the webpage. It's persisted across visits.

There are a bunch of branch links all over the page
pointing to various different points within various
different mobile apps.

there's no registration on website.

I want to add/inject that cookie/id to all branch links on page
so that when user clicks link taking her to app store
and installs app or already has app and re-opens it,
their web activity can be joined with their app activity
within the analytics provider.

any guidance on this use case?

thanks.

**Comment by aaustin** [comment]
@sirvon Thanks for the note. 

There are 2 options here:
1. Use the web SDK to generate the links on page load with the dynamic content . This is the call to do it https://github.com/BranchMetrics/Web-SDK#createlink. You'll also need to init before making that call.
2. Dynamically structure a link using string formatting https://github.com/BranchMetrics/Branch-Public-API#structuring-a-dynamic-deeplink This way, you don't actually create the link until the user clicks it, but you tell us all the parameters you want embedded in it using the base64 encoded dictionary.

I hope this helps!

**Comment by sirvon** [comment]
dynamically create the link.
niceee
thanks, it helps greatly
