### ISSUE TITLE
branch.close() fails even when init has been called

### ISSUE THREAD

**Issue by kpowerinfinity** [BranchMetrics/Web-SDK#73]
Hello,

I am building a cordova application in angularjs. Somehow the first click opens the app correctly - with the right set of JSON arguments passed originally but from future clicks it just opens up the play store and when I click "open" on the play store, the arguments originally called are not provided in the callback (+clicked_branch_link is false).

Is there something I might be missing in this?

Krishna.

**Comment by wedgybo** [comment]
I'm running into this as well. It's like the data never seems to update from the first install

**Comment by kpowerinfinity** [comment]
What I figured was that the branch-cordova-sdk automatically calls close()
so when I was calling it within my code on 'pause' it was throwing the
error. I commented out my own code, and it works fine. Hope that helps.

**Comment by aaustin** [comment]
@wedgybo did you get this sorted? I'll close this issue if so.

**Comment by wedgybo** [comment]
Yea this is fine! I thought it might have been related to my issue but it wasn't.

**Comment by aaustin** [comment]
Awesome
